# Generated by Django 5.1.7 on 2025-07-10 05:55

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VE', verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('independiente', models.BooleanField(default=True, verbose_name='Independiente')),
                ('foto_operador', models.ImageField(blank=True, null=True, upload_to='operadores/', verbose_name='Foto del Operador')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'unique_together': {('nombre', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Placa')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.1)], verbose_name='Alto (metros)')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.6)], verbose_name='Ancho (metros)')),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(12.2)], verbose_name='Largo (metros)')),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto del Vehículo')),
                ('codigo_qr', models.ImageField(upload_to='codigos_qr/', verbose_name='Código QR')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('razon_inactividad', models.TextField(blank=True, null=True, verbose_name='Razón de Inactividad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.operador', verbose_name='Operador')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Vuelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Registro')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vueltas', to='arpeta.asignacion', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Vuelta',
                'verbose_name_plural': 'Vueltas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(fields=('operador', 'vehiculo', 'fecha_asignacion'), name='unique_operador_vehiculo_fecha'),
        ),
    ]
